### ISSUE TITLE
Review Questionnaire page does not display any data

### ISSUE THREAD

**Issue by karentom** [springernature/snics-employee#105]
![image](https://user-images.githubusercontent.com/17595871/51297188-4cec2a00-19ed-11e9-81f6-bee8da6d58ad.png)

**Comment by karentom** [comment]
Seems it may be related to questionnaires that have a blank question because I have examples where this works.
https://github.com/springernature/snics-questionnaire/issues/48

**Comment by harshadporwal** [comment]
![image](https://user-images.githubusercontent.com/43807299/51299104-3c6b9c00-1a4d-11e9-91d8-3cdc683db255.png)

Fixed and working

**Comment by karentom** [comment]
@harshadporwal This is the review questionnaire page in the employee portal. It is still not working

**Comment by harshadporwal** [comment]
![image](https://user-images.githubusercontent.com/43807299/51305173-29ae9280-1a60-11e9-8dc3-f9f64421a568.png)

Fixed in both now management and employee portal

**Comment by mohammadsiddiqui** [comment]
@karentom  actually accidentally we have deleted a question from the database and as a result of which all these issues with the questionnaires started showing up.
